package com.rule

import com.discount.model.FinalBillCalculation


rule "Regular when amount is less then 5K"

	when 
		FinalBillCalculationObject: FinalBillCalculation(customerType =="Regular") &&  FinalBillCalculation(amount > "0" && amount <= "5000" )
	then
		
		FinalBillCalculationObject.setDiscountAmount(0);
	end

rule "Regular when amount is less then 10K"
	
	when 
		FinalBillCalculationObject: FinalBillCalculation(customerType =="Regular") &&  FinalBillCalculation(amount>"5000" && amount <="10000")
	then	
		FinalBillCalculationObject.setDiscountAmount(0 + ( FinalBillCalculationObject.getAmount() - 5000) * 0.10);		
	end

rule "Regular when amount is greater then 10K"
	
	when 
		FinalBillCalculationObject: FinalBillCalculation(customerType =="Regular") &&  FinalBillCalculation( amount >"10000")
	then	
		FinalBillCalculationObject.setDiscountAmount(0+ 5000 * 0.10 + ( FinalBillCalculationObject.getAmount() - 10000) * 0.20);		
	end



rule "Premium when amount is less then 4K"

	when 
		FinalBillCalculationObject: FinalBillCalculation(customerType =="Premium") &&  FinalBillCalculation(amount > "0" && amount <= "4000" )
	then
		FinalBillCalculationObject.setDiscountAmount( FinalBillCalculationObject.getAmount()*.10);	
	end


rule "Premium when amount is less then 8K"
	
	when 
		FinalBillCalculationObject: FinalBillCalculation(customerType =="Premium") &&  FinalBillCalculation(amount>"4000" && amount <="8000")
	then
	
	FinalBillCalculationObject.setDiscountAmount(4000 * 0.10 + ( FinalBillCalculationObject.getAmount() - 4000) * 0.15);
		
	end

rule "Premium when amount is less then 12K"
	
	when 
		FinalBillCalculationObject: FinalBillCalculation(customerType =="Premium") &&  FinalBillCalculation(amount>"8000" && amount <="12000")
	then	
		
		FinalBillCalculationObject.setDiscountAmount(4000 * 0.10 + (4000) * 0.15 + (FinalBillCalculationObject.getAmount() - 8000) * 0.20);

	end
rule "Premium when amount is greater then 12K"
	
	when 
		FinalBillCalculationObject: FinalBillCalculation(customerType =="Premium") &&  FinalBillCalculation(amount >"12000")
	then	
		FinalBillCalculationObject.setDiscountAmount(4000 * 0.10 + (4000) * 0.15 + (4000) * 0.20 + (FinalBillCalculationObject.getAmount() - 12000) * 0.30);		
	end
